### ISSUE TITLE
I have a Duchy in my deck when I didn't buy one!

### ISSUE THREAD

**Issue by nodnerb42** [eshapiro42/dominion-game#10]
![16071108345412801697872322549115](https://user-images.githubusercontent.com/75501330/101207494-b2c41800-363e-11eb-80a4-e5ccb721bfe8.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eshapiro42** [comment]
You're absolutely sure you didn't type the wrong number by accident? Could you <kbd>CTRL</kbd>+<kbd>F</kbd and search for "bought a Duchy" if you still have the game open?

**Comment by eshapiro42** [comment]
User error related to #11. @nodnerb42 did not realize that the number to select must always be chosen from the most recently shown table.
