### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by racoonsmakeokayfriends** [eshapiro42/dominion-game#107]
Add a favicon so my bookmark bar is nicer also other reasons

**Comment by racoonsmakeokayfriends** [comment]
[icons8-castle-ios-16-glyph-favicons.zip](https://github.com/eshapiro42/dominion-game/files/12255146/icons8-castle-ios-16-glyph-favicons.zip)

**Comment by eshapiro42** [comment]
I think it should be sufficient to just place `favicon.ico` into the `client/public` directory.

If that doesn't work, try adding something like this into `app.py`:

```
@app.route("/favicon.ico")
def home(path):
    return send_from_directory("client/public", "favicon.ico)
```
