### ISSUE TITLE
I selected #2 for Moneylender, then it told me "That is not a valid choice" and moved Moneylender to #1 Not

### ISSUE THREAD

**Issue by nodnerb42** [eshapiro42/dominion-game#11]
![16071110182822480629992801966647](https://user-images.githubusercontent.com/75501330/101207790-223a0780-363f-11eb-87cf-add4806b751d.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eshapiro42** [comment]
The number you input is always the number on the _most recently shown_ table. Moneylender was number 2 in your hand but number 1 in the table of things you could buy.
