### ISSUE TITLE
General CSS Tweaks

### ISSUE THREAD

**Issue by racoonsmakeokayfriends** [eshapiro42/dominion-game#111]
- [ ] Move chat icon:  right: 15px; top: 10px;

**Comment by eshapiro42** [comment]
You'll want to modify `client/src/components/toasts.svelte`.

You'll probably want to add an ID to the `fa-message` within the `<main>` tag and set the corresponding CSS in the `<style>` tag.

**Comment by eshapiro42** [comment]
We should also make the background color of Attack cards a smidge darker.
