### ISSUE TITLE
When the Contraband card is played, scroll down to the Supply section

### ISSUE THREAD

**Issue by racoonsmakeokayfriends** [eshapiro42/dominion-game#134]
When the contraband card is played, the player to the left is supposed to pick a card the player can't play this round. This isn't a bug, it does work correctly, just a quality of game suggestion. Most necessary user actions are "in your face" or at least at the top of the page. It was jarring for the game to just stop when I actually just had to scroll down to the Supply section and select a card.

**Comment by eshapiro42** [comment]
Hmm, it's scrolling for me. Is it possible you had [/#Supply]() in your URL bar at the time?
